const images = [
  //{ original: require("./imgs/screenshot_imgs/001.jpg"), thumbnail: require("./imgs/screenshot_imgs/001.jpg") },
  { original: require("./imgs/screenshot_imgs/002.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/002.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/003.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/003.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/004.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/004.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/005.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/005.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/006.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/006.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/007.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/007.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/008.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/008.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/009.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/009.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/010.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/010.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/011.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/011.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/012.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/012.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/013.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/013.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/014.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/014.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/015.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/015.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/016.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/016.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/017.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/017.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/018.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/018.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/019.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/019.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/020.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/020.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/021.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/021.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/022.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/022.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/023.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/023.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/024.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/024.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/025.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/025.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/026.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/026.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/027.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/027.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/028.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/028.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/029.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/029.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/030.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/030.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/031.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/031.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/032.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/032.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/033.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/033.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/034.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/034.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/035.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/035.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/036.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/036.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/037.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/037.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/038.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/038.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/039.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/039.jpg")*/ },
  { original: require("./imgs/screenshot_imgs/040.jpg")/*, thumbnail: require("./imgs/screenshot_imgs/040.jpg")*/ }
]

export default images
